export interface MockEmployee {
  id: string;
  nip: string;
  name: string;
  fullName: string;
  position: string;
  unitKerja: string;
  golRuang: string;
  email: string;
  phone: string;
  avatarUrl: string;
  birthDate?: string;
  education: string;
  careerHistory: string;
  achievements: string;
  bio: string;
  alamatDomisili?: string;
  tanggalLahir?: string;
  satuanKerja?: string;
  eselon2?: string;
  eselon3?: string;
  lokasiKerja?: string;
}

export const MOCK_EMPLOYEES: MockEmployee[] = [
  {
    id: 'emp-1',
    nip: '1986112700140350',
    name: 'Budi Sujatmiko',
    fullName: 'Budi Sujatmiko',
    position: 'Kepala Sistem Informasi',
    unitKerja: 'Pusat Data dan Informasi',
    golRuang: 'IV/a - Pembina',
    email: 'budisujatmiko@perpusnas.go.id',
    phone: '+62 812 1714 0352',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    education: 'S2 Magister Teknologi Informasi Universitas Indonesia',
    careerHistory: 'Staf IT (2015-2019), Kasubbag Infrastruktur Jaringan (2019-2023), Kepala Sistem Informasi (2023-Sekarang)',
    achievements: 'Inovator Transformasi Cloud Perpusnas 2024',
    bio: 'Berdedikasi untuk memajukan arsitektur sistem digital dan otomasi layanan perpustakaan berbasis kecerdasan buatan.',
    alamatDomisili: 'Jalan Imam Bonjol Nomor 1, RT 5/RW 4, Menteng, Kecamatan Menteng, Kota Jakarta Pusat',
    tanggalLahir: '27 November 1986',
    satuanKerja: 'Sistem Informasi',
    eselon2: 'Pusat Sistem Informasi',
    eselon3: 'Bidang Layanan Sistem Informasi',
    lokasiKerja: 'Jl. Medan Merdeka Selatan No. 11, Jakarta 10110',
  },
  {
    id: 'emp-2',
    nip: '198501152010011001',
    name: 'Drs. Bambang Sudirman, M.Hum.',
    fullName: 'Drs. Bambang Sudirman, M.Hum.',
    position: 'Pustakawan Ahli Madya',
    unitKerja: 'Direktorat Deposit dan Pengembangan Koleksi',
    golRuang: 'IV/b - Pembina Tk. I',
    email: 'bambang.sudirman@perpusnas.go.id',
    phone: '081122334455',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop',
    education: 'S2 Ilmu Perpustakaan Universitas Gadjah Mada',
    careerHistory: 'Pustakawan Muda (2010-2018), Pustakawan Madya (2018-Sekarang)',
    achievements: 'Pustakawan Berprestasi Tingkat Nasional Bidang Preservasi Naskah Nusantara 2023',
    bio: 'Meneliti dan merawat kekayaan intelektual manuskrip kuno Nusantara untuk generasi mendatang.',
  },
  {
    id: 'emp-3',
    nip: '199003202015022003',
    name: 'Siti Nurhaliza, S.Sos., M.I.Kom.',
    fullName: 'Siti Nurhaliza, S.Sos., M.I.Kom.',
    position: 'Pranata Humas Ahli Muda',
    unitKerja: 'Biro Hukum, Organisasi, dan Humas',
    golRuang: 'III/c - Penata',
    email: 'siti.nurhaliza@perpusnas.go.id',
    phone: '081344556677',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop',
    education: 'S2 Ilmu Komunikasi Universitas Padjadjaran',
    careerHistory: 'Staf Media Sosial (2015-2020), Pranata Humas Ahli Muda (2020-Sekarang)',
    achievements: 'Penghargaan Tata Kelola Komunikasi Publik Terbaik K/L 2024',
    bio: 'Menyebarkan literasi dan kecintaan membaca melalui strategi komunikasi modern.',
  },
  {
    id: 'emp-4',
    nip: '198807122012011002',
    name: 'Hendra Setiawan, S.T., M.Kom.',
    fullName: 'Hendra Setiawan, S.T., M.Kom.',
    position: 'Pranata Komputer Ahli Madya',
    unitKerja: 'Pusat Data dan Informasi',
    golRuang: 'IV/a - Pembina',
    email: 'hendra.setiawan@perpusnas.go.id',
    phone: '081298765432',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
    education: 'S2 Ilmu Komputer Institut Teknologi Bandung',
    careerHistory: 'System Engineer (2012-2017), Lead Database Administrator (2017-2022), Pranata Komputer Ahli Madya (2022-Sekarang)',
    achievements: 'Arsitek Integrasi Data Single Sign-On Perpusnas 2023',
    bio: 'Fokus pada keamanan siber, ketahanan pangkalan data terdistribusi, dan layanan big data.',
  },
  {
    id: 'emp-5',
    nip: '199204052016022001',
    name: 'Ratna Dewi Kusuma, S.I.Pust.',
    fullName: 'Ratna Dewi Kusuma, S.I.Pust.',
    position: 'Pustakawan Ahli Pertama',
    unitKerja: 'Direktorat Standarisasi dan Akreditasi',
    golRuang: 'III/b - Penata Muda Tk. I',
    email: 'ratna.dewi@perpusnas.go.id',
    phone: '081567891234',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=500&fit=crop',
    education: 'S1 Ilmu Perpustakaan Universitas Airlangga',
    careerHistory: 'Staf Asesor Perpustakaan Sekolah (2016-2021), Pustakawan Ahli Pertama (2021-Sekarang)',
    achievements: 'Penyusun Pedoman Akreditasi Perpustakaan Khusus 2024',
    bio: 'Mendorong peningkatan mutu dan standarisasi layanan perpustakaan di seluruh pelosok negeri.',
  },
  {
    id: 'emp-6',
    nip: '198711032011011003',
    name: 'Agus Priyono, S.E., M.M.',
    fullName: 'Agus Priyono, S.E., M.M.',
    position: 'Analis Kebijakan Ahli Muda',
    unitKerja: 'Biro Perencanaan dan Keuangan',
    golRuang: 'III/d - Penata Tk. I',
    email: 'agus.priyono@perpusnas.go.id',
    phone: '081398712345',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop',
    education: 'S2 Magister Manajemen Keuangan Universitas Diponegoro',
    careerHistory: 'Analis Anggaran (2011-2018), Analis Kebijakan Ahli Muda (2018-Sekarang)',
    achievements: 'Penghargaan Opini WTP Tata Kelola Anggaran Perpusnas',
    bio: 'Pengelolaan anggaran berbasis kinerja demi ketercapaian target literasi nasional.',
  },
  {
    id: 'emp-7',
    nip: '199308192018022002',
    name: 'dr. Farah Nabila, Sp.Ok.',
    fullName: 'dr. Farah Nabila, Sp.Ok.',
    position: 'Dokter Ahli Pertama',
    unitKerja: 'Klinik Pratama & Layanan Kesehatan Pegawai',
    golRuang: 'III/b - Penata Muda Tk. I',
    email: 'farah.nabila@perpusnas.go.id',
    phone: '081234599887',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=500&fit=crop',
    education: 'Spesialis Kedokteran Okupasi FKUI',
    careerHistory: 'Dokter Umum RSUD (2015-2018), Dokter Spesialis Kesehatan Kerja Perpusnas (2018-Sekarang)',
    achievements: 'Pelopor Program Ergonomi Sehat Kerja bagi Pegawai Perpusnas 2023',
    bio: 'Menjaga kesehatan fisik dan kenyamanan ergonomis seluruh insan kerja perpustakaan.',
  },
  {
    id: 'emp-8',
    nip: '198402142008011002',
    name: 'Dr. Joko Susanto, M.Si.',
    fullName: 'Dr. Joko Susanto, M.Si.',
    position: 'Kepala Pusat Pembinaan Pustakawan',
    unitKerja: 'Pusat Pembinaan Pustakawan',
    golRuang: 'IV/c - Pembina Utama Muda',
    email: 'joko.susanto@perpusnas.go.id',
    phone: '081188776655',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop',
    education: 'S3 Manajemen Pendidikan Universitas Negeri Jakarta',
    careerHistory: 'Widyaiswara (2008-2016), Kepala Bidang Pelatihan (2016-2022), Kapusbin Pustakawan (2022-Sekarang)',
    achievements: 'Penerima Satyalancana Karya Satya XX Tahun 2024',
    bio: 'Meningkatkan kompetensi, sertifikasi, dan profesionalisme pustakawan Indonesia.',
  },
  {
    id: 'emp-9',
    nip: '199505102019022001',
    name: 'Nadia Rahmadani, S.Pd., M.A.',
    fullName: 'Nadia Rahmadani, S.Pd., M.A.',
    position: 'Pengembang Bahan Ajar & Literasi',
    unitKerja: 'Pusat Pengembangan Perpustakaan Sekolah/Madrasah',
    golRuang: 'III/b - Penata Muda Tk. I',
    email: 'nadia.rahmadani@perpusnas.go.id',
    phone: '081223344556',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop',
    education: 'S2 Ilmu Pendidikan Budaya University of Melbourne',
    careerHistory: 'Staf Literasi Anak (2019-2022), Pengembang Kurikulum Literasi (2022-Sekarang)',
    achievements: 'Inisiator Pojok Baca Ceria Anak Pulau Terluar 2024',
    bio: 'Menumbuhkan budaya gemar membaca sejak usia dini melalui media belajar interaktif.',
  },
  {
    id: 'emp-10',
    nip: '198909282014011004',
    name: 'Rian Hidayat, S.Sos., M.P.A.',
    fullName: 'Rian Hidayat, S.Sos., M.P.A.',
    position: 'Analis Kepegawaian Ahli Muda',
    unitKerja: 'Biro SDM dan Umum',
    golRuang: 'III/c - Penata',
    email: 'rian.hidayat@perpusnas.go.id',
    phone: '081399887711',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=500&fit=crop',
    education: 'S2 Master of Public Administration Universitas Gadjah Mada',
    careerHistory: 'Staf Mutasi & Promosi (2014-2019), Analis Kepegawaian Ahli Muda (2019-Sekarang)',
    achievements: 'Implementasi Sistem Merit Kepegawaian Kategori Sangat Baik 2024',
    bio: 'Mewujudkan tata kelola SDM aparatur yang profesional, transparan, dan akuntabel.',
  },
  {
    id: 'emp-11',
    nip: '199106152015022002',
    name: 'Dewi Anjarwati, S.Hum.',
    fullName: 'Dewi Anjarwati, S.Hum.',
    position: 'Konservator Naskah Kuno',
    unitKerja: 'Pusat Preservasi dan Alih Media',
    golRuang: 'III/c - Penata',
    email: 'dewi.anjarwati@perpusnas.go.id',
    phone: '081299112233',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&h=500&fit=crop',
    education: 'S1 Sastra Jawa Universitas Sebelas Maret',
    careerHistory: 'Laboran Konservasi Kertas (2015-2020), Konservator Naskah Kuno (2020-Sekarang)',
    achievements: 'Pemulihan Manuskrip Daun Lontar Abad ke-16',
    bio: 'Menyelamatkan fisik naskah kuno nusantara dari kerapuhan dan kepunahan.',
  },
  {
    id: 'emp-12',
    nip: '198603212009011001',
    name: 'Eko Prasetyo, S.Kom.',
    fullName: 'Eko Prasetyo, S.Kom.',
    position: 'Administrator Jaringan Komputer',
    unitKerja: 'Pusat Data dan Informasi',
    golRuang: 'III/d - Penata Tk. I',
    email: 'eko.prasetyo@perpusnas.go.id',
    phone: '081199882244',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop',
    education: 'S1 Teknik Informatika Universitas Bina Nusantara',
    careerHistory: 'Network Admin (2009-2016), Senior Security Analyst (2016-Sekarang)',
    achievements: 'Sertifikasi Keamanan Jaringan CISSP & CEH',
    bio: 'Memastikan integritas jaringan dan ketersediaan layanan portal 24/7 tanpa henti.',
  },
  {
    id: 'emp-13',
    nip: '199411082017022003',
    name: 'Maya Indahsari, S.I.Pust., M.Hum.',
    fullName: 'Maya Indahsari, S.I.Pust., M.Hum.',
    position: 'Pustakawan Layanan Referensi',
    unitKerja: 'Direktorat Pelayanan Perpustakaan',
    golRuang: 'III/b - Penata Muda Tk. I',
    email: 'maya.indahsari@perpusnas.go.id',
    phone: '081377889900',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=500&fit=crop',
    education: 'S2 Ilmu Perpustakaan Universitas Padjadjaran',
    careerHistory: 'Pustakawan Referensi Khusus (2017-Sekarang)',
    achievements: 'Layanan Terbaik Bintang Lima Survei Kepuasan Pemustaka 2024',
    bio: 'Membantu pemustaka, peneliti, dan akademisi menemukan rujukan ilmiah yang akurat.',
  },
  {
    id: 'emp-14',
    nip: '198305142007011003',
    name: 'Ir. Ahmad Zulkarnain, M.Sc.',
    fullName: 'Ir. Ahmad Zulkarnain, M.Sc.',
    position: 'Koordinator Alih Media Digital',
    unitKerja: 'Pusat Preservasi dan Alih Media',
    golRuang: 'IV/b - Pembina Tk. I',
    email: 'ahmad.zulkarnain@perpusnas.go.id',
    phone: '081122778899',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop',
    education: 'S2 Digital Humanities Leiden University',
    careerHistory: 'Fotografer Reprografi (2007-2014), Koordinator Digitalisasi (2014-Sekarang)',
    achievements: 'Digitalisasi Lebih dari 50.000 Judul Buku Langka Nasional',
    bio: 'Menjembatani warisan masa lalu dengan teknologi visual resolusi tinggi.',
  },
  {
    id: 'emp-15',
    nip: '199602282020022002',
    name: 'Annisa Putri Wardani, S.Ds.',
    fullName: 'Annisa Putri Wardani, S.Ds.',
    position: 'Desainer Grafis & Multimedia',
    unitKerja: 'Biro Hukum, Organisasi, dan Humas',
    golRuang: 'III/a - Penata Muda',
    email: 'annisa.putri@perpusnas.go.id',
    phone: '081288990011',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=500&fit=crop',
    education: 'S1 Desain Komunikasi Visual Institut Kesenian Jakarta',
    careerHistory: 'Multimedia Specialist (2020-Sekarang)',
    achievements: 'Desain Identitas Visual Pameran Buku Internasional Perpusnas 2024',
    bio: 'Memvisualisasikan literasi lewat infografis cerdas, estetik, dan komunikatif.',
  },
  {
    id: 'emp-16',
    nip: '198901042013011002',
    name: 'Fauzi Rahman, S.IP., M.A.',
    fullName: 'Fauzi Rahman, S.IP., M.A.',
    position: 'Pengelola Kerja Sama Antarlembaga',
    unitKerja: 'Biro Hukum, Organisasi, dan Humas',
    golRuang: 'III/d - Penata Tk. I',
    email: 'fauzi.rahman@perpusnas.go.id',
    phone: '081312345678',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=500&fit=crop',
    education: 'S2 Hubungan Internasional Universitas Indonesia',
    careerHistory: 'Diplomasi Kebudayaan (2013-2018), Kerja Sama Antarlembaga (2018-Sekarang)',
    achievements: 'Fasilitator MoU Kerja Sama dengan 12 Perpustakaan Nasional Dunia',
    bio: 'Menjalin kolaborasi strategis perpustakaan lintas benua.',
  },
  {
    id: 'emp-17',
    nip: '199210172016022004',
    name: 'Tri Wahyuni, S.E., Ak.',
    fullName: 'Tri Wahyuni, S.E., Ak.',
    position: 'Auditor Pertama',
    unitKerja: 'Inspektorat',
    golRuang: 'III/b - Penata Muda Tk. I',
    email: 'tri.wahyuni@perpusnas.go.id',
    phone: '081233445566',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop',
    education: 'S1 Akuntansi Universitas Brawijaya',
    careerHistory: 'Staf Verifikasi Keuangan (2016-2021), Auditor Internal (2021-Sekarang)',
    achievements: 'Sertifikasi Auditor Forensik Sektor Publik 2023',
    bio: 'Menjunjung integritas pengawasan intern demi tata kelola pemerintahan yang bersih.',
  },
  {
    id: 'emp-18',
    nip: '198706242011011005',
    name: 'Danang Tri Wicaksono, S.S.',
    fullName: 'Danang Tri Wicaksono, S.S.',
    position: 'Kurator Koleksi Monograf & Peta Kuno',
    unitKerja: 'Direktorat Deposit dan Pengembangan Koleksi',
    golRuang: 'III/d - Penata Tk. I',
    email: 'danang.wicaksono@perpusnas.go.id',
    phone: '081198765432',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
    education: 'S1 Sejarah Universitas Indonesia',
    careerHistory: 'Kurator Peta & Kartografi (2011-Sekarang)',
    achievements: 'Penerbitan Katalog Peta Nusantara Abad 17-19',
    bio: 'Meneliti rute pelayaran dan peta kuno untuk membuka tabir sejarah maritim Nusantara.',
  },
  {
    id: 'emp-19',
    nip: '199407302018022001',
    name: 'Aulia Nurul Hikmah, S.T.',
    fullName: 'Aulia Nurul Hikmah, S.T.',
    position: 'Pengelola Infrastruktur Cloud & Server',
    unitKerja: 'Pusat Data dan Informasi',
    golRuang: 'III/b - Penata Muda Tk. I',
    email: 'aulia.nurul@perpusnas.go.id',
    phone: '081255667788',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=500&fit=crop',
    education: 'S1 Teknik Elektro dan Teknologi Informasi UGM',
    careerHistory: 'Cloud DevOps Engineer (2018-Sekarang)',
    achievements: 'Penerapan Kubernetes Cluster di Pusat Data Nasional',
    bio: 'Menjaga skalabilitas sistem perpustakaan saat melayani jutaan pengakses online.',
  },
  {
    id: 'emp-20',
    nip: '198509122009011003',
    name: 'Lukman Hakim, S.Sos., M.I.P.',
    fullName: 'Lukman Hakim, S.Sos., M.I.P.',
    position: 'Pustakawan Ahli Madya',
    unitKerja: 'Pusat Pembinaan Pustakawan',
    golRuang: 'IV/a - Pembina',
    email: 'lukman.hakim@perpusnas.go.id',
    phone: '081399881122',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop',
    education: 'S2 Ilmu Informasi dan Perpustakaan Universitas Padjadjaran',
    careerHistory: 'Penguji Uji Kompetensi Pustakawan (2014-Sekarang)',
    achievements: 'Penulis Buku Standar Kompetensi Kerja Nasional Indonesia (SKKNI) Perpustakaan',
    bio: 'Menyiapkan generasi pustakawan masa depan yang adaptif terhadap era disrupsi digital.',
  },
  {
    id: 'emp-21',
    nip: '199312012017011002',
    name: 'Dimas Prasojo, S.Kom.',
    fullName: 'Dimas Prasojo, S.Kom.',
    position: 'Pranata Komputer Ahli Pertama',
    unitKerja: 'Pusat Data dan Informasi',
    golRuang: 'III/a - Penata Muda',
    email: 'dimas.prasojo@perpusnas.go.id',
    phone: '081388776655',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop',
    education: 'S1 Sistem Informasi ITS Surabaya',
    careerHistory: 'Frontend & UI Engineer (2017-Sekarang)',
    achievements: 'Pemenang Hackathon Layanan Publik Nasional 2023',
    bio: 'Menciptakan antarmuka pengguna portal intranet yang intuitif, cepat, dan ramah pengguna.',
  },
  {
    id: 'emp-22',
    nip: '199103142015022001',
    name: 'Nurul Hidayati, S.Pd., M.Ed.',
    fullName: 'Nurul Hidayati, S.Pd., M.Ed.',
    position: 'Widyaiswara Ahli Muda',
    unitKerja: 'Pusat Pendidikan dan Pelatihan',
    golRuang: 'III/c - Penata',
    email: 'nurul.hidayati@perpusnas.go.id',
    phone: '081277665544',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop',
    education: 'S2 Master of Education Monash University',
    careerHistory: 'Trainer Literasi Informasi (2015-Sekarang)',
    achievements: 'Fasilitator Utama Pelatihan Pustakawan Desa Berprestasi 2024',
    bio: 'Mendidik dan melatih agen-agen literasi hingga pelosok desa nusantara.',
  },
  {
    id: 'emp-23',
    nip: '198804022012011003',
    name: 'Arif Wibowo, S.H., M.H.',
    fullName: 'Arif Wibowo, S.H., M.H.',
    position: 'Analis Hukum Ahli Muda',
    unitKerja: 'Biro Hukum, Organisasi, dan Humas',
    golRuang: 'III/d - Penata Tk. I',
    email: 'arif.wibowo@perpusnas.go.id',
    phone: '081133445566',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    education: 'S2 Magister Ilmu Hukum Universitas Indonesia',
    careerHistory: 'Advokasi Hukum & HKI (2012-Sekarang)',
    achievements: 'Penyusun Regulasi Perlindungan Hak Cipta Karya Cetak dan Karya Rekam',
    bio: 'Menegakkan kepatuhan hukum dan perlindungan karya intelektual bangsa.',
  },
  {
    id: 'emp-24',
    nip: '199705152021022001',
    name: 'Salma Khairunnisa, S.I.Pust.',
    fullName: 'Salma Khairunnisa, S.I.Pust.',
    position: 'Pustakawan Layanan Disabilitas',
    unitKerja: 'Direktorat Pelayanan Perpustakaan',
    golRuang: 'III/a - Penata Muda',
    email: 'salma.khairunnisa@perpusnas.go.id',
    phone: '081266554433',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=500&fit=crop',
    education: 'S1 Ilmu Perpustakaan Universitas Indonesia',
    careerHistory: 'Pustakawan Layanan Khusus Disabilitas Netra (2021-Sekarang)',
    achievements: 'Pengembangan Audiobook Braille Digital untuk Tunanetra',
    bio: 'Mewujudkan perpustakaan inklusif tanpa batas bagi seluruh anak bangsa.',
  },
  {
    id: 'emp-25',
    nip: '198608292010011004',
    name: 'Bagus Pratama, S.Si.',
    fullName: 'Bagus Pratama, S.Si.',
    position: 'Analis Statistik & Big Data',
    unitKerja: 'Pusat Data dan Informasi',
    golRuang: 'III/d - Penata Tk. I',
    email: 'bagus.pratama@perpusnas.go.id',
    phone: '081399001122',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
    education: 'S1 Statistika Institut Pertanian Bogor',
    careerHistory: 'Analis Tren Kunjungan & Minat Baca (2010-Sekarang)',
    achievements: 'Dashboard Realtime Indeks Pembangunan Literasi Masyarakat (IPLM)',
    bio: 'Menganalisis data statistik untuk perumusan kebijakan literasi nasional yang tepat sasaran.',
  },
];

export const LIST_UNIT_KERJA = [
  'Semua Unit Kerja',
  'Pusat Data dan Informasi',
  'Direktorat Deposit dan Pengembangan Koleksi',
  'Direktorat Pelayanan Perpustakaan',
  'Direktorat Standarisasi dan Akreditasi',
  'Pusat Pembinaan Pustakawan',
  'Pusat Preservasi dan Alih Media',
  'Pusat Pengembangan Perpustakaan Sekolah/Madrasah',
  'Pusat Pendidikan dan Pelatihan',
  'Biro Hukum, Organisasi, dan Humas',
  'Biro SDM dan Umum',
  'Biro Perencanaan dan Keuangan',
  'Inspektorat',
  'Klinik Pratama & Layanan Kesehatan Pegawai',
];
